# Generated by Django 4.2 on 2026-05-26 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=10)),
                ('uploaded_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('fuel_type', models.CharField(max_length=100)),
                ('scope', models.IntegerField(default=1)),
                ('emission_factor_kg_per_litre', models.FloatField(help_text='Emission factor in kgCO2e per litre')),
            ],
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RawIngestionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kgco2e', models.FloatField(blank=True, null=True)),
                ('scope', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.CharField(max_length=100)),
                ('meter_id', models.CharField(max_length=100)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('tariff_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('period_days', models.IntegerField(blank=True, null=True)),
                ('original_consumption', models.FloatField(blank=True, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('normalized_kwh', models.FloatField(blank=True, null=True)),
                ('demand_kva', models.FloatField(blank=True, null=True)),
                ('bill_amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('grid_emission_factor', models.FloatField(blank=True, help_text='kgCO2e/kWh', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionrun')),
                ('raw_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawingestionrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kgco2e', models.FloatField(blank=True, null=True)),
                ('scope', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_id', models.CharField(max_length=100)),
                ('expense_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('CAR', 'Car'), ('TRAIN', 'Train')], max_length=20)),
                ('traveler_id', models.CharField(blank=True, max_length=100, null=True)),
                ('traveler_name', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('distance_was_calculated', models.BooleanField(default=False)),
                ('class_of_travel', models.CharField(blank=True, max_length=50, null=True)),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('amount_inr', models.FloatField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('is_international', models.BooleanField(default=False)),
                ('emission_factor_used', models.FloatField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionrun')),
                ('raw_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawingestionrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SAPRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kgco2e', models.FloatField(blank=True, null=True)),
                ('scope', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant_code', models.CharField(max_length=50)),
                ('plant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_code', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('original_quantity', models.FloatField(blank=True, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('normalized_quantity_liters', models.FloatField(blank=True, null=True)),
                ('normalized_quantity_kg', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('movement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionrun')),
                ('raw_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawingestionrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='ingestion.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
