# Generated by Django 4.2 on 2026-05-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallookup',
            name='emission_factor_kg_per_litre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='utilityrecord',
            name='grid_emission_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('record_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('record_id', models.UUIDField()),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
