toml id="h9e2jf"
[phases.setup]
nixPkgs = ["gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate && gunicorn breathe_esg.wsgi:application --bind 0.0.0.0:$PORT"

